# Generated by Django 4.2 on 2025-08-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=100)),
                ('question', models.TextField(default='')),
                ('option1', models.CharField(default='', max_length=255)),
                ('option2', models.CharField(default='', max_length=255)),
                ('option3', models.CharField(default='', max_length=255)),
                ('option4', models.CharField(default='', max_length=255)),
                ('correct_option', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=100)),
                ('goal', models.CharField(default='', max_length=100)),
                ('courses', models.TextField(default='')),
                ('youtube_links', models.TextField(default='')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
